### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Remove the `class_alias` to let the PHPUnit namespace alias in `bootstrap.php` because the PHPUnit version `5+` will use the class-based PHPUnit namespace.
- Set the `satooshi/php-coveralls:^1.0` because `codeclimate/php-test-reporter:dev-master` requires that.

### CODE REVIEW

**Comment by schnittstabil** [comment]
Many thanks for taking time reviewing the tests.
> PHPUnit version `5+` will use the class-based PHPUnit namespace.

Strictly speaking, this isn't correct: PHPUnit `<=5.6` needs the `class_alias`, thus it is only true for `>=5.7`.
Anyway, I've planned to remove it when PHP `5.6` reaches it EOL (1st Jan 2019) and I do not see any harm keeping it until than.

:+1: The other changes look good to me.

**Comment by peter279k** [comment]
@schnittstabil, thank you for your reply.
If possible, how about letting this package require `php-7.0` at least and define in `composer.json`.
Also, remove the `php-5.6` test from `.travis.yml`.
I can do this in this PR.

What do you think? Thanks.

**Comment by schnittstabil** [comment]
PHP `7.0` isn't _actively supported_ anymore ([Supported Versions](http://php.net/supported-versions.php)). Hence, why not target `7.2` right away? `>=5.6`, `7.1` and `7.2` consumers could still use the current version of `csrf-tokenservice`, thus everybody can softly migrate to `>=7.2`.

**Comment by peter279k** [comment]
Let `php-7.2` be the right way to define in `composer.json` :+1:.

**Comment by peter279k** [comment]
@schnittstabil , I've let this package require `php-7.2` in the latest commit.
Please check it that.

Thanks.

**Comment by schnittstabil** [comment]
@peter279k Many thanks for contributing!

**Pull request merged**
